### ISSUE TITLE
Pls add icon

### ISSUE THREAD

**Issue by coliff** [cfjedimaster/vscode-csslint#1]
An icon for each extension shows in list of installed extensions and on the VS Code Extension Marketplace. It'd be nice to add one for vscode-csslint.

If you'd like me to create a quick one and open a PR with it - let me know. :-)

**Comment by cfjedimaster** [comment]
Yes please - I'd gladly take a PR on this.

**Comment by coliff** [comment]
Ok cool. I opened a PR (#2). There are Bithound errors but I don't think they are related to the changes I made....

**Comment by cfjedimaster** [comment]
Sorry for the delay!

**Comment by coliff** [comment]
thanks for adding it. I just got the extension update :-)
